services:
  - type: web
    name: backend
    env: node
    region: sao-paulo
    plan: starter
    buildCommand: cd backend && npm install --include=dev && npm run build
    startCommand: cd backend && NODE_ENV=production npm start
    healthCheckPath: /health
